# Generated by Django 2.1.15 on 2020-10-21 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, default='')),
                ('preferred_name', models.CharField(max_length=100, null=True)),
                ('avatar_url', models.CharField(max_length=255, null=True)),
                ('discord_name', models.CharField(max_length=100, null=True)),
                ('github_username', models.CharField(max_length=100)),
                ('codepen_username', models.CharField(max_length=100, null=True)),
                ('fcc_profile_url', models.CharField(max_length=255, null=True)),
                ('current_level', models.IntegerField(choices=[(1, 'Level One'), (2, 'Level Two')], default=1)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('timezone', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
