# Generated by Django 2.1.15 on 2020-10-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201021_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='last_name',
        ),
    ]
